### ISSUE TITLE
Converting WANNIERT_HR.dat for unit cell to  that of SUPPERCELL

### ISSUE THREAD

**Issue by Nazari-Fariba** [Z2PackDev/TBmodels#113]
Hi,
By using the following commands I have tried to produce wannier_hr.dat file for silicon supercell. the file is produced in model3.
 But the values are different. The model2 file is differing from wannier_hr.dat file of the silicon unit cell, too. 
The next problem is belonging to model4, this command does not run.
I would appreciate your comments.
import tbmodels
import numpy as np
model = tbmodels.Model.from_wannier_folder(folder='/d......./TBmodels-trunk/examples/silicon/build/', prefix='silicon')
supercell_model = model.supercell((4, 4, 1))
model2=model.to_hr_file('model_hr.dat')
model3=supercell_model.to_hr_file('supercell_model_hr.dat')
model4 = tbmodels.Model.from_hr_file('model_hr.dat')

**Comment by greschd** [comment]
> But the values are different.

That's to be expected, TBmodels also takes into account the `_wsvec.dat` file, and maps WF which happen to be outside the unit cell back into it.

> model4 = tbmodels.Model.from_hr_file('model_hr.dat')

That command doesn't exist. You may be looking for [from_wannier_files](https://tbmodels.greschd.ch/en/latest/reference.html#tbmodels.Model.from_wannier_files).

Overall, `*_hr.dat` files aren't a great storage medium for tight-binding models. Mostly because, due to their ASCII nature, values are very truncated. But also, part of the data (positions, unit cell) needs to be stored in separate files.

**Comment by Nazari-Fariba** [comment]
​Hi,
Thanks for the quick reply.
In the attachment you can find two files.

 * Silsicon_hr.dat , this file is produced by  wannier90.
 * model_hr.dat, this file is produced by TB. I mean  before producing supercell  , I have tried to reproduce  silsicon_hr.dat via TB. 
When I have  compared the two files it seems that the difference s are more than the truncation errors.  Would you please help me to understand the problem.

Regards
Fariba 

On Tue, 05/10/2022 11:58 PM, Dominik Gresch ***@***.***> wrote:
> 
> 

But the values are different.
That's to be expected, TBmodels also takes into account the _wsvec.dat file, and maps WF which happen to be outside the unit cell back into it.

> 

model4 = tbmodels.Model.from_hr_file('model_hr.dat')
That command doesn't exist. You may be looking for from_wannier_files.
Overall, *_hr.dat files aren't a great storage medium for tight-binding models. Mostly because, due to their ASCII nature, values are very truncated. But also, part of the data (positions, unit cell) needs to be stored in separate files.

**Comment by greschd** [comment]
>TBmodels also takes into account the _wsvec.dat file, and maps WF which happen to be outside the unit cell back into it.

This changes the _hr.dat values. They are not naturally comparable, without reverting this mapping. It's more productive to compare band structures to validate the tight-binding model.
