### ISSUE TITLE
win parser should properly consider units

### ISSUE THREAD

**Issue by giovannipizzi** [Z2PackDev/TBmodels#24]
Now, if units are specified, the win parser fails.

E.g. with this in the .win:
```
begin atoms_cart
ang
W 0. 0. 0.
end atoms_cart
```
it fails. The same for `begin unit_cell_cart`.

For now, as we only use `ang` (that anyway is the default) we just strip in the parser the following lines:
```
lines = (l for l in lines if 'ang' != l)
```
but of course it is subideal.
One should read the first line after 'begin', that could be already a value, or contain either `bohr` or `ang`.
If specified, one should use this as units (and convert the values where needed).
If not specified, one should check the global flag that specifies units for the whole file, and if not specified, assume the default is angstrom.

**Comment by greschd** [comment]
For the ``unit_cell_cart``, this is handled in https://github.com/Z2PackDev/TBmodels/blob/36357ae6d6f3b69f711bd41c82b4d4d1a09ac3fe/tbmodels/_tb_model.py#L690, although this doesn't properly take into account the default set in ``length_unit``.

The ``atoms_cart`` isn't parsed at all (except for putting it into a mapping), the positions are taken from the .xyz file. There, again the default should be properly considered.

Do you know if the default applies also to the .xyz file, or only the .wout?

**Comment by giovannipizzi** [comment]
I think the xyz is always ang by definition of the format, but it should be double-checked in the cannier code to make sure this is actually what is implemented.

In our case we got an exception for `atoms_cart` because it was complaining of `ang`, I don't know if because while testing at that stage we weren't passing a xyz yet - but I also realise looking at the source now that we are working with an older version... so maybe this problem does not apply anymore (except taking into account `length_unit`).

**Comment by greschd** [comment]
Could you maybe check which version / input file you had an exception for ``atoms_cart`` with? I quickly looked at the code for the 1.1 release, and while the unit isn't handled there, I don't see where the ``atoms_cart`` is used. I'm wondering if the issue might still be there in the current version.

**Comment by greschd** [comment]
From checking a simple example, it seems that the .xyz file is indeed written in Angstrom regardless of the ``length_unit`` specified.
