### ISSUE TITLE
Running pytest from base directory gives errors

### ISSUE THREAD

**Issue by michaelwimmer** [Z2PackDev/TBmodels#9]
I'm not sure if that's the desired behavior, but running `pytest` from the base directory gives many test failures as the sample data from `tests/samples` is not found.

**Comment by greschd** [comment]
Ah, I guess I could make that more generic. The "intended" way of running the tests is from the ``tests/`` directory.

**Comment by greschd** [comment]
This is fixed -- I get the absolute path of the test file, and the sample file relative to it.
